language: php
php:
  - 5.4
  - 5.6

env:
    - TEMP_FIXTURE_DIR=$TRAVIS_BUILD_DIR/tmp
    
services:
    - mongodb

before_script:
  - mkdir -p tmp
  - phpenv config-add config.travis.ini
  - composer update
  - mkdir -p build/logs

script:
  - phpunit --config phpunit.travis.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
